name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Makes file available for executing
      run: chmod 777 BuildTest.sh
    - name: Run the build file
      run: ./BuildTest.sh
